### PR TITLE
Fixed the sign problems leading to bad initialization of the fd_limit in sparsebundle_read_buf

### PR DESCRIPTION
**Pull request by fedxa**
Also some inessential sign fixes used to get rid of gcc warning

### CODE REVIEW

**Comment by torarnv** [comment]
Thanks! Will massage and merge as soon as I can

**Comment by torarnv** [comment]
fd_limit issue was fixed in f3ccd20bd6393b05c9949810feb0e0b366b86348

**Comment by jeroenhabets** [comment]
Three years later I get the same issues while compiling on Ubuntu 16.04.

Is this project still maintained?

**Comment by torarnv** [comment]
Are you referring to the sign warnings? The fd_limit issue was fixed in f3ccd20

**Comment by torarnv** [comment]
Thanks for your contribution, apologies for the (long long) delay! This PR is now tracked in #24

**Pull request closed without merging**
